#!/usr/bin/env python3
"""Serve the built page locally with the exact headers from vercel.json.

Why this is in the repo rather than a scratch file: without it, nothing ever
exercises the Content-Security-Policy. smoke.sh drives index.html over file://,
where response headers do not apply at all, so a policy that blanks production
would sail through a fully green CI run. The CSP is generated by build.py from
per-script hashes, and a hash that does not match its script blocks that script
— blocking the host script serves a blank page. That failure has to be caught
here, not by a user.

Usage: python3 src/csp-serve.py <root> <port>
"""
import http.server
import json
import os
import sys

ROOT = sys.argv[1]
PORT = int(sys.argv[2])

with open(os.path.join(ROOT, "vercel.json"), encoding="utf-8") as fh:
    cfg = json.load(fh)

HEADERS = [
    (h["key"], h["value"])
    for rule in cfg.get("headers", [])
    if rule.get("source") == "/(.*)"
    for h in rule.get("headers", [])
    # HSTS is meaningless over plain http and would poison localhost for
    # every other project on this machine.
    if h["key"] != "Strict-Transport-Security"
]


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=ROOT, **kw)

    def end_headers(self):
        for k, v in HEADERS:
            self.send_header(k, v)
        super().end_headers()

    def log_message(self, *a):
        pass


http.server.HTTPServer(("127.0.0.1", PORT), Handler).serve_forever()
